### ISSUE TITLE
Got next exception

### ISSUE THREAD

**Issue by YevhenDuma** [Remitly/verdaccio-s3-storage#15]
#### Additional information:

 - `$ NODE_DEBUG=request verdaccio` display request calls (verdaccio <--> uplinks)
 - `$ DEBUG=express:* verdaccio` enable extreme verdaccio debug mode (verdaccio api)
 - `$ npm -ddd` prints:
 - `$ npm config get registry` prints:
 - Verdaccio terminal output
 - Which (Windows, OS X/macOS, or Linux) environment are you running verdaccio?: Amazon Linux on Ec2 instance
 - Verdaccio configuration file, eg: `cat ~/.config/verdaccio/config.yaml`
store:
  s3-storage:
    bucket: <some bucket>
    keyPrefix: storage
auth:
  htpasswd:
    file: ./htpasswd
    max_users: -1
uplinks:
  npmjs:
    url: https://registry.npmjs.org/
packages:
  '**':
    access: $authenticated
    publish: $authenticated
    proxy: npmjs
listen:
  - 0.0.0.0:4873
logs:
  - {type: stdout, format: pretty, level: http}
  - Container Options:
   - Docker?: No
   - Kubernetes? No

#### Additional verbose log:

fatal--- uncaught exception, please report this
TypeError: readStream.destroy is not a function
    at ReadTarball.readTarballStream.abort (/home/verdaccio/node_modules/verdaccio-s3-storage/lib/s3PackageManager.js:250:18)
    at ReadTarball.stream.abort (/home/verdaccio/node_modules/verdaccio/build/lib/local-storage.js:525:27)
    at ReadTarball.localStream.on.err (/home/verdaccio/node_modules/verdaccio/build/lib/storage.js:177:19)
    at emitOne (events.js:96:13)
    at ReadTarball.emit (events.js:188:7)
    at ReadTarball.<anonymous> (/home/verdaccio/node_modules/verdaccio/build/lib/local-storage.js:531:16)
    at emitOne (events.js:101:20)
    at ReadTarball.emit (events.js:188:7)
    at PassThrough.readStream.on.err (/home/verdaccio/node_modules/verdaccio-s3-storage/lib/s3PackageManager.js:243:25)
    at emitOne (events.js:96:13)

**Comment by snetty** [comment]
also experiencing this bug, is there any news?

**Comment by YevhenDuma** [comment]
I've moved to EFS, so no more issue like this.
