### ISSUE TITLE
Exception when using uplinks

### ISSUE THREAD

**Issue by Jbonavita** [Remitly/verdaccio-s3-storage#28]
I'm using uplinks to the public npm. When the user requests a package that is not in our local npm, we get an exception and the service stops. If we only request local packages, everything works perfect.

>  fatal--- uncaught exception, please report this
TypeError: readStream.destroy is not a function
    at ReadTarball.readTarballStream.abort (/usr/lib/node_modules/verdaccio-s3-storage/lib/s3PackageManager.js:262:18)
    at ReadTarball.stream.abort (/usr/lib/node_modules/verdaccio/build/lib/local-storage.js:526:27)
    at ReadTarball.localStream.on.err (/usr/lib/node_modules/verdaccio/build/lib/storage.js:177:19)
    at emitOne (events.js:96:13)
    at ReadTarball.emit (events.js:188:7)
    at ReadTarball.<anonymous> (/usr/lib/node_modules/verdaccio/build/lib/local-storage.js:532:16)
    at emitOne (events.js:101:20)
    at ReadTarball.emit (events.js:188:7)
    at PassThrough.readStream.on.err (/usr/lib/node_modules/verdaccio-s3-storage/lib/s3PackageManager.js:255:25)
    at emitOne (events.js:96:13)

# path to a directory with all packages
storage: ./storage

store:
  s3-storage:
    bucket: private-bucket
    keyPrefix: # some-prefix # optional, has the effect of nesting all files in a subdirectory
    region: us-east-1 # optional, will use aws s3's default behavior if not specified
    endpoint: # https://{service}.{region}.amazonaws.com # optional, will use aws s3's default behavior if not specified
    s3ForcePathStyle: false # optional, will use path style URLs for S3 objects
    accessKeyId: # your-access-key-id # optional, aws accessKeyId for private S3 bucket
    secretAccessKey: # your-secret-access-key # optional, aws secretAccessKey for private S3 bucket

Is there a setting I forgot to set?

**Comment by Jbonavita** [comment]
Any suggestions?

**Comment by martin31821** [comment]
@Jbonavita Did you find a solution?

**Comment by martin31821** [comment]
Works for me in 0.2.1 and the official verdaccio-aws-s3-plugin
