### ISSUE TITLE
UnhandledPromiseRejectionWarning: InvalidAccessKeyId: nul

### ISSUE THREAD

**Issue by HunsonlAbadeer** [Remitly/verdaccio-s3-storage#29]
AWS-SDK for node, cant spot AccessKeyId and secret. This what i get on strat up
`
 warn --- config file  - /app/config.yaml
 warn --- Plugin successfully loaded: verdaccio-s3-storage
(node:8) UnhandledPromiseRejectionWarning: InvalidAccessKeyId: null
    at Request.extractError (/usr/local/lib/node_modules/verdaccio-s3-storage/node_modules/aws-sdk/lib/services/s3.js:585:35)
    at Request.callListeners (/usr/local/lib/node_modules/verdaccio-s3-storage/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/verdaccio-s3-storage/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/verdaccio-s3-storage/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/verdaccio-s3-storage/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/verdaccio-s3-storage/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/verdaccio-s3-storage/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/verdaccio-s3-storage/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/verdaccio-s3-storage/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/verdaccio-s3-storage/node_modules/aws-sdk/lib/sequential_executor.js:116:18)`

My env vars:
`
ENV AWS_ACCESS_KEY_ID <some_key>
ENV AWS_SECRET_ACCESS_KEY <some_key>
ENV AWS_S3_ENDPOINT http://<my.s3.path>:7480
ENV AWS_S3_PATH_STYLE true
`
My verdaccio .conf:
`
# path to a directory with all packages
storage: ./storage

store:
  s3-storage:
    endpoint:  http://<my.s3.path>:7480
    bucket: proxy.npm.registry
    accessKeyId: <some_key>
    secretAccessKey: <some_key>
`

**Comment by ved54321** [comment]
facing a similar issue, the plugin seems to be only working with public bucket.
