### ISSUE TITLE
Error: Cannot find module 'lodash'

### ISSUE THREAD

**Issue by konstantinj** [Remitly/verdaccio-s3-storage#31]
My Dockerfile is this:
```
FROM verdaccio/verdaccio:4
RUN npm install verdaccio-s3-storage
```

and I'm getting this error:
```
docker run -it --rm --name verdaccio -p 4873:4873 verdaccio
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module 'lodash'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/app/build/lib/bootstrap.js:9:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

also tried version 3. Same error.

Should this plugin still work with the latest version?

**Comment by juanpicado** [comment]
hi @konstantinj 

https://verdaccio.org/docs/en/docker#plugins

```
FROM verdaccio/verdaccio

USER root

ENV NODE_ENV=production

RUN npm i && npm install verdaccio-s3-storage

USER verdaccio
```

**Comment by konstantinj** [comment]
Yes thanks, found some more examples like this in the meantime.
